---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  #vars_files:
  #  - ../vault.yml
  connection: local
  tasks:
    - name: Authenticate and get an API token from Automation Hub
      ansible.hub.ah_token:
        ah_host: "{{ aap_hostname }}"
        ah_username: "{{ aap_username }}"
        ah_password: "{{ aap_password }}"
        ah_path_prefix: 'galaxy'  # this is for private automation hub
        ah_verify_ssl: false
    - name: Fixing format
      ansible.builtin.set_fact:
        ah_token: "{{ ah_token['token'] }}"
    - name: Authenticate and get an API token from Automation Platform 
      ansible.platform.token:
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        description: "Temporary CaC Dispatch Token"
        scope: "write"
        state: present
        aap_validate_certs: false
      register: gateway_token_login

    #- name: Enforce the token for all subsequent tasks
    #  ansible.builtin.set_fact:
    #    aap_token: "{{ gateway_token_login.token.token }}"
    - name: call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

    - name: starting of EDA configuration
      vars:
        eda_aap_cred_name: "myaap"
        eda_gitlab_cred_name: "kam-github"
        eda_project_name: "Splunk-EDA-Project"
      block:
        - name: create eda AAP credentials
          ansible.eda.credential:
            name: "{{ eda_aap_cred_name }}"
            controller_host: "https://{{ aap_hostname }}"
            controller_username: "{{ aap_username }}"
            controller_password: "{{ aap_password }}"
            description: aap credentials
            credential_type_name: 'Red Hat Ansible Automation Platform'
            organization_name: Default
            validate_certs: false
            inputs:
              username: "{{ aap_username }}"
              password: "{{ aap_password }}"
              host: "https://{{ aap_hostname }}/api/controller/"
              verify_ssl: false


        - name: create eda credentials
          ansible.eda.credential:
            name: "{{ eda_gitlab_cred_name }}"
            controller_host: "https://{{ aap_hostname }}"
            controller_username: "{{ aap_username }}"
            controller_password: "{{ aap_password }}"
            description: my GitHub Credential
            credential_type_name: 'Source Control'
            organization_name: "config_as_code"
            validate_certs: false
            inputs:
              username: kamlendu1982
              ssh_key_data: "{{ gitlab_token }}"
       
        - name: create eda project
          ansible.eda.project:
            name: "{{ eda_project_name }}"
            controller_host: "https://{{ aap_hostname }}"
            controller_username: "{{ aap_username }}"
            controller_password: "{{ aap_password }}"
            url: git@github.com:kamlendu1982/HomeLabEDA.git
            credential: "{{ eda_gitlab_cred_name }}"
            organization_name: "config_as_code"
            validate_certs: false
            sync: true
          #tags:
          #  - never 

        - name: create a rulebook activation
          ansible.eda.rulebook_activation:
            name: splunk-action-caac
            description: Hook to listen for changes in GitHub
            project: "{{ eda_project_name }}"
            #project: mqtt-https
            organization_name: "config_as_code"
            rulebook_name: "test_splunk_webhook.yml"
            decision_environment: "Default Decision Environment"
            eda_credentials:
              - "{{ eda_aap_cred_name }}"
            enabled: true
            state: present

        - name: Use api lookup plugin to run assertions
          ansible.builtin.assert:
            that:
              - project_lookup | map(attribute='name') is contains('my_project')
              - project_lookup | map(attribute='name') is contains('my_project_clone')
          tags:
            - assertions
            - never
          vars:
            project_lookup: "{{ lookup('infra.eda_configuration.eda_api', 'projects', host=eda_hostname, username=eda_username,
                password=eda_password, verify_ssl=false, query_params=qp) }}"
            qp:
              url: 'https://github.com/ansible/event-driven-ansible.git'
...
