---
controller_credentials:
  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: config_as_code
    description: aap admin account
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: hub_service_account
    credential_type: automation_hub
    organization: config_as_code
    description: automation hub api account
    inputs:
      hostname: "{{ aap_hostname }}"
      username: "{{ aap_service_account_username }}"
      token: "{{ ah_token }}"
      verify_ssl: false

  - name: hub_certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ ah_hostname }}/pulp_ansible/galaxy/rh-certified/"
      token: "{{ ah_token }}"

  - name: hub_published
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ ah_hostname }}/pulp_ansible/galaxy/published/"
      token: "{{ ah_token }}"

  - name: hub_community
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ ah_hostname }}/pulp_ansible/galaxy/community/"
      token: "{{ ah_token }}"

  - name: hub_community_infra_repo
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ ah_hostname }}/pulp_ansible/galaxy/community-infra-repo/"
      token: "{{ ah_token }}"

  - name: cr_ah
    credential_type: Container Registry
    organization: config_as_code
    inputs:
      host: "{{ ah_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: vault
    credential_type: Vault
    organization: config_as_code
    description: vault password
    inputs:
      vault_password: "{{ vault_pass }}"
  - name: windows_password
    credential_type: Machine
    organization: windows_usecase
    description: administrator password
    inputs:
      username: "Administrator"
      password: "?f@ukUp50ezttmU)R=Rs?i10ddbyH*s;"
...
