---
controller_execution_environments:
  - name: "supported"
    image: "{{ ah_hostname }}/ee-supported-rhel8"
    pull: always
    credential: cr_ah

  - name: "minimal"
    image: "{{ ah_hostname }}/ee-minimal-rhel8"
    pull: always
    credential: cr_ah

...
