---
controller_groups:
  - name: windows_group
    inventory: windows
    variable:
      ansible_connection: winrm
      ansible_port: 5985
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
    hosts:
      - windows_host
