---
controller_inventory_sources:
  - name: config_as_code_source
    organization: Default
    source: "Sourced from a Project"
    source_project: Inventory_project
    source_path: inventory/static_git_inv.yml
    inventory: sample_dynamic
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
...
