---
controller_templates:
  - name: controller_config
    project: config_as_code
    job_type: run
    #playbook: playbooks/controller_config.yml
    playbook: sample_playbooks/access_config_from_git.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    #limit: "{{ env }}"
    verbosity: 0
    credentials:
      - aap_admin
      - vault
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: ah_config
    project: config_as_code
    job_type: run
    #playbook: playbooks/hub_config.yml
    playbook: sample_playbooks/get_remote_hostname.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    #limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault

  - name: eda_config
    project: config_as_code
    job_type: run
    playbook: sample_playbooks/access_config_from_git.yml
    #playbook: playbooks/eda_config.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    #limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault

  - name: build_execution_environments
    project: config_as_code
    job_type: run
    #playbook: playbooks/build_ee.yml
    playbook: sample_playbooks/get_remote_hostname.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    verbosity: 0

  - name: build_custom_collections
    project: config_as_code
    job_type: run
    #playbook: playbooks/custom_collection.yml
    playbook: playbooks_eda/say-what.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    #limit: "{{ env }}"
    verbosity: 0
    credentials:

  - name: console_token_refresh
    project: config_as_code
    job_type: run
    playbook: sample_playbooks/access_config_from_git.yml
    #playbook: playbooks/console_token_refresh.yml
    inventory: config_as_code
    execution_environment: minimal
    concurrent_jobs_enabled: false
    #limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault

  - name: collection_sync
    project: config_as_code
    job_type: run
    playbook: sample_playbooks/access_config_from_git.yml
    #playbook: playbooks/sync_collections.yml
    inventory: config_as_code
    execution_environment: minimal
    concurrent_jobs_enabled: false
    #limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault
...
