---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest
dependencies:
  galaxy: requirements.yml
additional_build_files:
  - src: ./ansible.cfg
    dest: configs/
options:
  package_manager_path: /usr/bin/microdnf
additional_build_steps:
  prepend_galaxy: |
    COPY configs/ansible.cfg /etc/ansible/ansible.cfg
  prepend_final: |
    COPY configs/ansible.cfg /etc/ansible/ansible.cfg
