---
collections:
  - name: infra.ee_utilities
    version: 4.0.0
  - name: infra.aap_configuration
    version: 3.1.0
  - name: containers.podman
    version: 1.16.3
  - name: community.general
    version: 10.4.0
  - name: ansible.hub
    version: 1.0.0
  - name: ansible.platform
    version: 2.5.20250213
  - name: ansible.controller
    version: 4.6.8
